added indicator/latest endpoint, added ability to return geo and onto…
jataware/dojo-deprecated pull request #164
Opened 2022-02-09 01:28 UTC by marshHawk4

…logies with flag , updated validation

2022-02-09 15:53 UTC, mattprintz requested changes
In depth, nit-picky review requested and delivered.

2022-02-09 15:53 UTC, mattprintz commented on api/src/indicators.py
> +    print(results)
Remove unneeded print statements please.

2022-02-09 15:53 UTC, mattprintz commented on api/src/indicators.py
> +def get_latest_indicators(size=10000) -> DojoSchema.IndicatorSearchResult:
FastAPI doesn't ACTUALLY infer the response_model from the return type annotation. This is something that I only learned relatively recently. Instead we want to set it in the response_model instead as well as in the annotation like in the original code.
(Also applies to other endpoint below)

2022-02-09 15:53 UTC, mattprintz commented on api/src/indicators.py
> +    results = es.search(index='indicators', body=q,size=size)
Remember to use [PEP-8](https://www.python.org/dev/peps/pep-0008/) formatting throughout (spaces after commas, spaces around equals, spaces after `:`, etc)

2022-02-09 15:53 UTC, mattprintz commented on api/src/indicators.py
> +    query: str = Query(None), size: int = 10, scroll_id: str = Query(None),ontologies:bool=True ,geo:bool=True
A parameter named "ontologies" or "geo" might be confusing as to whether it's a bool or expecting you to pass in ontologies/geo values to match against.
A better naming scheme would be `inlcude_ontologies` and `include_geography`
(Also PEP-8 reminder)

2022-02-09 15:53 UTC, mattprintz commented on api/src/indicators.py
> +    reducedData = resp
This statement probably doesn't do what you think it does.
In this case, both `resp` and `reducedData` will be a reference to the same object in memory and modifying one also modifies the other. At the end of the function, if you print out `resp` you'll see that it has also been reduced.

This isn't bad to create a new reference to the object with a different name, but in cases like the above, it is likely that having both variables will imply to a reader that the two objects are different when in reality they are not.

I would recommend changing `resp` to `indicator_data`, optionally stripping out the values if desired, and having a single return of `indicator_data`, letting it be clear from the code that you are stripping out the values if the flags are sent.

(Also, camel_case variables per PEP-8)

2022-02-09 15:53 UTC, mattprintz commented on api/src/indicators.py
> +    if not ontologies or geo:
This condition is just an inversion of the condition on line 91 and could have been included in an `else:` clause for a simpler, clearer flow.

2022-02-09 15:53 UTC, mattprintz commented on api/src/indicators.py
> +        for i,indicator in enumerate(reducedData['results']):
Remember what I said above about the variables being references to the same objects? That applies to values in a list or dictionary as well (and pretty much anywhere where there's a relationship).
As such, you can just modify the objects directly without having to jump through hoops with enumerating the values in the list.

For example:
```
for i, indicator in enumerate(reducedData['results']):
    reducedData['results'][i]['foo'] = 'bar'
    del reducedData['results'][i]['foobar']
```
is functionally equivalent to:
```
for indicator in reducedData['results']:
    indicator['foo'] = bar
    del indicator['foobar']
```
And is much easier to read, understand, and follow.
This goes for the sub-loops too:
```
for indicator in reducedData['results']:
    for output in indicator['qualifier_outputs']:
        output['ontologies'] = {...}
```

Caveat: This only works on ALTERATIONS to the object being looped over itself. If you wanted to REPLACE the value with something else, this does not work.
So:
```
for i, obj in enumerate(items):
    if obj['val'] == 5:
        items[i] = None
```
is NOT equivalent to
```
for obj in items:
    if obj['val'] == 5:
        obj = None
```   

This is because in the latter case, obj is just a reference and `obj = None` just means point the variable to be a ref that points to None. You're not actually changing the data of the object that the ref refers to, and are not changing what the reference the list uses.

2022-02-09 15:53 UTC, mattprintz commented on api/validation/IndicatorSchema.py
> +    )
Descriptions on the two fields are the same, but should they be?

Also, `name` and `to_name` are confusing to me. I can't really tell how they should be used and "alias name of the value" doesn't really clear things up for me.

Without searching through the code to confirm, based on my hunch, I would imagine better names would be: `orig_value` and `final value` or something similar. Not sure if this is predefined elsewhere though.

Also, I would think that since these are Optional we would need to set the default value instead of using `...` since the default is ambiguous.
Actually, thinking about it, should these even be optional? Sure, the list of aliases should be optional, but the values here should probably be required, even if someone passes in an empty string. No?

2022-02-10 20:55 UTC, marshHawk4 commented on api/src/indicators.py
> +def get_latest_indicators(size=10000) -> DojoSchema.IndicatorSearchResult:
Fixed this with help

2022-02-10 21:15 UTC, marshHawk4 commented on api/src/indicators.py
> +    reducedData = resp
Done.

2022-02-10 21:18 UTC, marshHawk4 commented on api/src/indicators.py
> +    if not ontologies or geo:
I think I fixed this.

2022-02-10 21:30 UTC, marshHawk4 commented on api/validation/IndicatorSchema.py
> +    )
The name and to_name are defined in Spacetag and Phantom. If it is a big issue I can change them all.

2022-02-11 00:03 UTC, marshHawk4 commented on api/src/indicators.py
> +    print(results)
Done

2022-02-11 00:04 UTC, marshHawk4 commented on api/src/indicators.py
> +    results = es.search(index='indicators', body=q,size=size)
Ran black and that should solve these

2022-02-11 00:04 UTC, marshHawk4 commented on api/src/indicators.py
> +    query: str = Query(None), size: int = 10, scroll_id: str = Query(None),ontologies:bool=True ,geo:bool=True
Updated names

2022-02-11 00:04 UTC, marshHawk4 commented on api/src/indicators.py
> +        for i,indicator in enumerate(reducedData['results']):
That is very cool. Thanks for writing this out. I updated the code and it worked first try.

2022-02-11 14:26 UTC, mattprintz commented on api/validation/IndicatorSchema.py
> +    )
If this is just reflecting names used elsewhere, this is fine. Thanks.

2022-02-16 21:32 UTC, mattprintz approved these changes
Looks good.

2022-02-16 21:52 UTC, merged