Add `/indicators/{indicator_id}/csv` endpoint
jataware/dojo-deprecated pull request #183
Opened 2022-07-11 16:50 UTC by fivegrant

This endpoint concatenates and converts all existing data on the fly and returns the resulting CSV.

2022-07-11 17:07 UTC, fivegrant commented
This PR addresses #181, but it only saves in the CSV format (as decided in our discussion @mattprintz @brandomr).

2022-07-11 17:07 UTC, fivegrant commented
This PR addresses #181, but it only saves in the CSV format (as decided in our discussion @mattprintz @brandomr).

2022-07-11 17:25 UTC, mattprintz commented on api/src/indicators.py
> +import io
This didn't actually get used, so can go ahead and remove/not include this import if the final result continues to not require the module.

2022-07-11 17:25 UTC, mattprintz commented on api/src/indicators.py
> +            dfs.append(df)
dfs could be defined as a list comprehension. This may simplify the code.

2022-07-11 17:25 UTC, mattprintz commented on api/src/indicators.py
> +        yield from result.to_csv(None, index=False)
I did a bit of testing and I don't think that this will quite do what we want.

The desire with streaming the data is that we would prefer to not load all of the data all at once in to memory as the files may be larger than the amount of free memory and it would be best to not run out of memory/crash. The idea then is to generate and output the data in chunks, where the chunk of memory is reused and so the maximum memory usage stays the same regardless of file size. I don't think that is happening here.

Will reach out in Slack to discuss further and look at options.

2022-07-11 17:27 UTC, mattprintz commented on api/src/indicators.py
> +@router.get("/indicators/{indicator_id}/csv")
I think that I would prefer the route to be "/indicators/{indicator_id}/download/csv" and if we add additional downloads they will be namespaced/grouped in a more coherent, natural way.

2022-07-11 17:28 UTC, fivegrant commented on api/src/indicators.py
> +import io
Sorry, artifact from previous solution. will remove

2022-07-12 12:33 UTC, fivegrant commented on api/src/indicators.py
> +        yield from result.to_csv(None, index=False)
Thanks for fixing this. Set up a PR for `mp/dataset-download` -> `feature/dataset-download`.

2022-07-13 15:04 UTC, fivegrant commented on api/src/indicators.py
> +    async def compress(content):
The speed is identical when breaking this out.

2022-07-13 17:56 UTC, mattprintz requested changes

2022-07-13 17:56 UTC, mattprintz commented on api/src/indicators.py
> +    def iter_csv():
Probably want async on this one too.

2022-07-13 17:56 UTC, mattprintz commented on api/src/indicators.py
> +       "deflate" in request.headers["accept-encoding"]:
```suggestion
    if "deflate" in request.headers.get("accept-encoding", ""):
```
I tend to prefer this syntax where we use dict.get() to return a default value of the expected type rather than checking for existence then checking for acceptability.

2022-07-13 17:56 UTC, mattprintz commented on api/src/indicators.py
Per PEP-8, we should have two spaces between function definitions.

2022-07-13 17:56 UTC, mattprintz commented on api/src/indicators.py
PEP-8 formatting.

2022-07-13 18:40 UTC, fivegrant commented on api/src/indicators.py
> +    def iter_csv():
I tried that earlier, but async generators aren't iterable. Let me see if I can get rid of the for loop in compress to get around it.

2022-07-13 19:55 UTC, fivegrant commented on api/src/indicators.py
added the extra space

2022-07-13 19:56 UTC, fivegrant commented on api/src/indicators.py
added space

2022-07-13 19:56 UTC, fivegrant commented on api/src/indicators.py
> +    def iter_csv():
Made `iter_csv` async

2022-07-13 19:56 UTC, fivegrant commented on api/src/indicators.py
> +       "deflate" in request.headers["accept-encoding"]:
fixed

2022-07-19 19:04 UTC, mattprintz approved these changes
Looks and works good.

2022-07-20 17:02 UTC, merged