Add `/model/status` endpoint
jataware/dojo-deprecated pull request #199
Opened 2022-08-15 19:53 UTC by fivegrant

The model status endpoint generates the statuses for each model. User can force a status to exist by passing in options that trigger default runs.

2022-08-16 16:02 UTC, mattprintz requested changes

2022-08-16 16:02 UTC, mattprintz commented on api/src/models.py
>  @router.put("/models/{model_id}")
PEP-8 spacing

```suggestion
    }


@router.put("/models/{model_id}")
```

2022-08-16 16:02 UTC, mattprintz commented on api/src/models.py
> +                return "running"
As discussed, we will not be kicking off runs from this API call. Happy to have a dedicated call to do so though.

2022-08-16 16:02 UTC, mattprintz commented on api/src/models.py
> +    return {model_id: status(model_id) for model_id in payload.model_ids}
Still investigating ways to aggregate to pull the status for the most recent runs for all models rather than needing to loop over a set that is provided.

2022-08-17 16:51 UTC, fivegrant commented on api/src/models.py
> +                return "running"
Let me know what you think of the new endpoint

2022-08-17 16:53 UTC, fivegrant commented on api/src/models.py
> +    return {model_id: status(model_id) for model_id in payload.model_ids}
Is it all right to resolve this since we are considering tabling this for now?

2022-09-15 21:32 UTC, merged