Versioning
jataware/dojo-deprecated pull request #97
Opened 2021-09-29 19:07 UTC by BecketTrotter

- validate all versioning creations with pydantic ([config](https://github.com/jataware/dojo/blob/ab1ac0fd127178f9ac47db90e695bd476e9448de/api/src/dojo.py#L148-L151), [directive](https://github.com/jataware/dojo/blob/ab1ac0fd127178f9ac47db90e695bd476e9448de/api/src/dojo.py#L104-L105), [accessory_file](https://github.com/jataware/dojo/blob/ab1ac0fd127178f9ac47db90e695bd476e9448de/api/src/dojo.py#L306-L309), [outputfile](https://github.com/jataware/dojo/blob/ab1ac0fd127178f9ac47db90e695bd476e9448de/api/src/dojo.py#L200-L203))
- model schema allows for optional [prev_version and next_version](https://github.com/jataware/dojo/blob/ab1ac0fd127178f9ac47db90e695bd476e9448de/api/validation/ModelSchema.py#L518-L524)
- updated doc strings for copy commands
- copy over accessory files, output files, directives, and configs for model versioning
  - assign new unique ids to all of these and link them to the new_model_id

2021-09-30 14:58 UTC, brandomr requested changes

2021-09-30 14:58 UTC, brandomr commented on api/src/dojo.py
> +    p = payload[0]
@BecketTrotter I don't think you need to specify this since `p` will be set from the last iteration of the loop just above it.

2021-09-30 14:58 UTC, brandomr commented on api/src/dojo.py
> +    for i in range(len(configs)):
Is there some reason this can't be `for config in configs:`?

2021-09-30 14:58 UTC, brandomr commented on api/src/dojo.py
> +    p = payload[-1]
Same as above...`p` should already be defined from the loop.

2021-09-30 14:58 UTC, brandomr commented on api/src/dojo.py
> +    for i in range(len(outputfiles)):
Can this be `for output in outputfiles`?

2021-09-30 14:58 UTC, brandomr commented on api/src/models.py
> +def version_model(model_id : str, payload : dict):
I'm considering whether this function should be called `increment_model_version`.... @BecketTrotter what do you think? It is longer....but more expressive. I'm torn.

2021-09-30 14:58 UTC, brandomr commented on api/src/models.py
> +    create_model(m)
@BecketTrotter I think for clarity this should use the `modify_model` function, in which case you'd just pass an `id` and a dict:

```
modify_model(id=model_id, payload={'next_version':new_id}
```

I think this is more clear that we're actually modifying a model in place.

2021-09-30 14:58 UTC, brandomr commented on api/src/models.py
> +    for x in payload.keys():
What is this doing? I don't think there ought to be a `payload` for this function? It should just require a `model_id`.

2021-09-30 14:58 UTC, brandomr commented on api/src/models.py
> +    return new_id
Since this is an API endpoint it should return a `Response` object like the other endpoints.

2021-09-30 14:58 UTC, brandomr commented on api/src/models.py
> +@router.get("/models/latest/")
This function should return something that is in the schema. See https://github.com/jataware/dojo/blob/master/api/src/models.py#L70-L76 or https://github.com/jataware/dojo/blob/master/api/src/models.py#L79-L85 for examples.

This makes things self-documenting in the swagger UI.

2021-09-30 15:10 UTC, BecketTrotter commented on api/src/models.py
> +def version_model(model_id : str, payload : dict):
@brandomr what about  function named `increment_version` under the models url so the url will be `/model/increment_version/{model_id}`

2021-10-11 14:34 UTC, brandomr approved these changes
@BecketTrotter looks good.

2021-10-11 14:34 UTC, brandomr commented on api/src/models.py
> +    copy_outputfiles(model_id, new_id)
Since these functions have internal error handling (returns `False` if not found) I think a future improvement could be to add some logging within the functions to log out that there was nothing to copy, etc.

2021-10-11 17:58 UTC, merged